[2024-11-13T07:15:54.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T07:15:54.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T07:15:37.465233+00:00 [queued]>
[2024-11-13T07:15:54.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T07:15:37.465233+00:00 [queued]>
[2024-11-13T07:15:54.112+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T07:15:54.119+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-13 07:15:37.465233+00:00
[2024-11-13T07:15:54.126+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=325) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-13T07:15:54.129+0000] {standard_task_runner.py:63} INFO - Started process 327 to run task
[2024-11-13T07:15:54.128+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-13T07:15:37.465233+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp1f886zuo']
[2024-11-13T07:15:54.131+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask dbt_test
[2024-11-13T07:15:54.177+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T07:15:37.465233+00:00 [running]> on host e3260ad76193
[2024-11-13T07:15:54.239+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T07:15:37.465233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T07:15:37.465233+00:00'
[2024-11-13T07:15:54.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T07:15:54.245+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T07:15:54.246+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/build_dbt --project-dir /opt/***/build_dbt']
[2024-11-13T07:15:54.261+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T07:15:55.769+0000] {subprocess.py:93} INFO - [0m07:15:55  Running with dbt=1.8.7
[2024-11-13T07:15:57.004+0000] {subprocess.py:93} INFO - [0m07:15:57  Registered adapter: snowflake=1.8.4
[2024-11-13T07:15:57.210+0000] {subprocess.py:93} INFO - [0m07:15:57  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-11-13T07:15:57.213+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-11-13T07:15:57.214+0000] {subprocess.py:93} INFO - - models.build_dbt.example
[2024-11-13T07:15:57.481+0000] {subprocess.py:93} INFO - [0m07:15:57  Found 2 models, 2 sources, 459 macros
[2024-11-13T07:15:57.493+0000] {subprocess.py:93} INFO - [0m07:15:57
[2024-11-13T07:15:57.497+0000] {subprocess.py:93} INFO - [0m07:15:57  Nothing to do. Try checking your model configs and model specification args
[2024-11-13T07:15:58.409+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-13T07:15:58.413+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T07:15:58.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-13T07:15:37.465233+00:00, execution_date=20241113T071537, start_date=20241113T071554, end_date=20241113T071558
[2024-11-13T07:15:58.553+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-13T07:15:58.606+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-13T07:15:58.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
