[2024-11-14T04:22:33.963+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T04:22:33.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T04:22:09.914233+00:00 [queued]>
[2024-11-14T04:22:33.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T04:22:09.914233+00:00 [queued]>
[2024-11-14T04:22:33.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T04:22:34.001+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-14 04:22:09.914233+00:00
[2024-11-14T04:22:34.013+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T04:22:34.017+0000] {standard_task_runner.py:63} INFO - Started process 4357 to run task
[2024-11-14T04:22:34.016+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-14T04:22:09.914233+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpdtxx0ef1']
[2024-11-14T04:22:34.025+0000] {standard_task_runner.py:91} INFO - Job 225: Subtask dbt_test
[2024-11-14T04:22:34.090+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T04:22:09.914233+00:00 [running]> on host 3627cdc70e56
[2024-11-14T04:22:34.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T04:22:09.914233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T04:22:09.914233+00:00'
[2024-11-14T04:22:34.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T04:22:34.166+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T04:22:34.167+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/build_dbt --project-dir /opt/***/build_dbt']
[2024-11-14T04:22:34.180+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T04:22:37.264+0000] {subprocess.py:93} INFO - [0m04:22:37  Running with dbt=1.8.7
[2024-11-14T04:22:38.556+0000] {subprocess.py:93} INFO - [0m04:22:38  Registered adapter: snowflake=1.8.4
[2024-11-14T04:22:38.830+0000] {subprocess.py:93} INFO - [0m04:22:38  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-11-14T04:22:38.833+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-11-14T04:22:38.835+0000] {subprocess.py:93} INFO - - models.build_dbt.example
[2024-11-14T04:22:39.018+0000] {subprocess.py:93} INFO - [0m04:22:39  Found 4 models, 1 snapshot, 2 sources, 459 macros
[2024-11-14T04:22:39.023+0000] {subprocess.py:93} INFO - [0m04:22:39
[2024-11-14T04:22:39.026+0000] {subprocess.py:93} INFO - [0m04:22:39  Nothing to do. Try checking your model configs and model specification args
[2024-11-14T04:22:40.197+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-14T04:22:40.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T04:22:40.265+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-14T04:22:09.914233+00:00, execution_date=20241114T042209, start_date=20241114T042233, end_date=20241114T042240
[2024-11-14T04:22:40.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-14T04:22:40.355+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-14T04:22:40.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
